# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'AutoCycleAdView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'                #https://github.com/onevcat/Kingfisher.git

end

target 'AutoCycleAdviewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'                #https://github.com/onevcat/Kingfisher.git

end
